all:
	@$(MAKE) -C square
	@$(MAKE) -C o-grid
	@$(MAKE) -C nozzle
	@$(MAKE) -C chamber_simple
	@$(MAKE) -C injector_simple
clean:
	@$(MAKE) -C square clean
	@$(MAKE) -C o-grid clean
	@$(MAKE) -C nozzle clean
	@$(MAKE) -C chamber_simple clean
	@$(MAKE) -C injector_simple clean
