all:
	@$(MAKE) -C square
	@$(MAKE) -C square_turned
	@$(MAKE) -C square_2blocks
	@$(MAKE) -C square_4blocks
clean:
	@$(MAKE) -C square clean
	@$(MAKE) -C square_turned clean
	@$(MAKE) -C square_2blocks clean
	@$(MAKE) -C square_4blocks clean
